### ISSUE TITLE
My audio icon disappears sometimes

### ISSUE THREAD

**Issue by Tedium-16** [VaughnValle/blue-sky#3] opened 2020-12-23 14:41 UTC
The volume icon that shows up next the wifi icon only show sometimes when I boot up my machine most times when I boot it isn't there the wifi icon is always there. I'm not sure what is the cause of this problem.

**Comment by Tedium16** [comment] 2020-12-24 22:09
The problem is no longer occuring you can close this issue

**Comment by VaughnValle** [comment] 2021-01-09 13:53
Good to hear :)

**Closed by VaughnValle** 2021-01-09 13:53 UTC
